name: 构建JD Scripts snapshot镜像

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "jd_scripts/Dockerfile.snapshot"
  repository_dispatch:
    types: jd_scripts_snapshot

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - id: repo_name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository_owner }}

      - name: 构建并推送到Dockerhub和ghcr.io镜像仓库
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./jd_scripts/Dockerfile.snapshot
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            akyakya/jd_scripts:snapshot
            ghcr.io/${{ steps.repo_name.outputs.lowercase }}/jd_scripts:snapshot
